### ISSUE TITLE
Unify the treatment of the word "reconnoiter"

### ISSUE THREAD

**Issue by jpnance** [standardebooks/mark-twain_roughing-it#10]
https://github.com/standardebooks/mark-twain_roughing-it/blob/4d34afbaa1c46a51e0c1f51d5296ec5ae7d68e5e/src/epub/text/chapter-40.xhtml#L15

The root word "reconnoiter" appears three times in "Roughing It":

1. As "reconnoiter" in Chapter 28.
2. As "reconnoitered" in Chapter 39.
3. As "reconnoitre" in Chapter 40 (referenced above).

I believe the third instance is an oversight within the 1913 scan--which Americanizes the spellings of many words, particularly "lustre" and "meagre"--so I think that we should change "reconnoitre" to "reconnoiter".

**Comment by acabal** [comment]
OK, I've gone ahead and done that. Thanks!
