### ISSUE TITLE
Lowercase the phrase "twenty-five dollars"

### ISSUE THREAD

**Issue by jpnance** [standardebooks/mark-twain_roughing-it#11]
https://github.com/standardebooks/mark-twain_roughing-it/blob/4d34afbaa1c46a51e0c1f51d5296ec5ae7d68e5e/src/epub/text/chapter-42.xhtml#L14

In the 1913 scan, this instance of "Twenty-Five Dollars" appears as "Twenty-five Dollars" but I believe this is an oversight within that edition as plenty of other instances of currency are treated with all lowercase letters.

https://github.com/standardebooks/mark-twain_roughing-it/blob/4d34afbaa1c46a51e0c1f51d5296ec5ae7d68e5e/src/epub/text/chapter-42.xhtml#L15

This instance of the phrase begins a sentence so it should obviously be capitalized but I think we should lowercase the word "dollars".

**Comment by acabal** [comment]
Done, thanks!
