### ISSUE TITLE
Change "good by" to "goodbye"?

### ISSUE THREAD

**Issue by jpnance** [standardebooks/mark-twain_roughing-it#12]
https://github.com/standardebooks/mark-twain_roughing-it/blob/4d34afbaa1c46a51e0c1f51d5296ec5ae7d68e5e/src/epub/text/chapter-43.xhtml#L30

The phrase "good by" is rendered as "good-by" in the 1913 scan but, of course, would be rendered as "goodbye" in modern text. I'm not sure what the preferred SE style is here.

**Comment by acabal** [comment]
Looks like an oversight by modernize-spelling. I've fixed it.
