### ISSUE TITLE
Change "'tother" to "t'other"?

### ISSUE THREAD

**Issue by jpnance** [standardebooks/mark-twain_roughing-it#13]
https://github.com/standardebooks/mark-twain_roughing-it/blob/4d34afbaa1c46a51e0c1f51d5296ec5ae7d68e5e/src/epub/text/chapter-50.xhtml#L17

This instance of "'tother" certainly seems to be a contraction of the phrase "the other" and so should be more properly rendered as "t'other". In fact, there's another instance of this contraction where it is rendered like that:

https://github.com/standardebooks/mark-twain_roughing-it/blob/4d34afbaa1c46a51e0c1f51d5296ec5ae7d68e5e/src/epub/text/chapter-54.xhtml#L21

**Comment by acabal** [comment]
Fixed, thanks!
