### ISSUE TITLE
Change several instances of "irruption" to "eruption"?

### ISSUE THREAD

**Issue by jpnance** [standardebooks/mark-twain_roughing-it#14]
https://github.com/standardebooks/mark-twain_roughing-it/blob/4d34afbaa1c46a51e0c1f51d5296ec5ae7d68e5e/src/epub/text/chapter-62.xhtml#L23

Referenced above is one of four separate usages of the word "irruption" in the text. These are rendered as they are in the scan but it seems like the more modern word would be "eruption". Confusingly, though, "eruption" also appears in the text (referenced below), so I'm not sure if I'm missing some subtle difference between the words or if it's just a bit of an oversight.

https://github.com/standardebooks/mark-twain_roughing-it/blob/4d34afbaa1c46a51e0c1f51d5296ec5ae7d68e5e/src/epub/text/chapter-73.xhtml#L25

**Comment by acabal** [comment]
irruption is its own word: https://www.merriam-webster.com/dictionary/irruption
