### ISSUE TITLE
Change "coacoanut" to "coconut" and retain all other instances of "coconut"?

### ISSUE THREAD

**Issue by jpnance** [standardebooks/mark-twain_roughing-it#15]
https://github.com/standardebooks/mark-twain_roughing-it/blob/4d34afbaa1c46a51e0c1f51d5296ec5ae7d68e5e/src/epub/text/chapter-63.xhtml#L11

This issue is a bit of a two-parter:

1. The referenced line includes the word "coacoanut", which, although it's rendered as "cocoanut" in the 1913 scan, would certainly seem to be our familiar word "coconut".
2. In fact, there are many more instances of the word "cocoanut" in the scan (but are presently rendered as "coconut" in the SE edition).

So, I'm suggesting that we update the line I referenced to "coconut" and just maintain all of the other instances as-is.

**Comment by acabal** [comment]
Good idea, I've gone ahead and done that. Thanks!
