### ISSUE TITLE
Incorrectly rendered instance of the word "stage-coach" in Chapter VI

### ISSUE THREAD

**Issue by jpnance** [standardebooks/mark-twain_roughing-it#4]
https://github.com/standardebooks/mark-twain_roughing-it/blob/7783976d2e13ba4c786c6b6b8cff419b358a8241/src/epub/text/chapter-6.xhtml#L12

"Think of it! He had absolute charge of the mails, express matter, passengers and stage, coach, until he delivered them to the next conductor, and got his receipt for them."

"stage, coach" should be amended to "stage-coach" as it appears in this scan of the book on page 54: https://archive.org/details/in.ernet.dli.2015.261235/page/n56/mode/1up

This error also exists in the original Project Gutenberg text so I'll submit that errata to them separately.

**Comment by acabal** [comment]
Thanks, this should be fixed now!

**Comment by jpnance** [comment]
I've made a mistake, sort of. The page scan I referenced in my issue is a different one than the scans mentioned in the source details for this book (sorry, I totally missed that those were provided). In the official Standard Ebooks source scans, the phrase is, indeed, rendered at it was before I opened this issue. It just seems wrong, though, doesn't it?

I've got a bevy of other things in this book that I've deemed as typos that I'm planning on submitting but a spot-check of several of them in the official scan shows that they, too, are actually rendered faithfully, despite them being rendered more sensibly (in my opinion, I suppose) in the alternative scan I've been looking at. So, I guess I have two questions: 1) Is there ever any sense of switching which scans we consider to be the reference material for a work?; 2) Should I check all my hypothetical submissions against the scans which are currently official and only send them in if they differ?

Apologies for any confusion on this!

Edit: If this works better as a mailing list thread, I'm happy to move it over there.

**Comment by acabal** [comment]
Typos in print are common, and different editions have different typos. Different editions also often have different punctuation that are not typos - just different editors or typesetters changing things for the sake of it. There is almost never such a thing as a "one true edition" in books.  

Typically we prefer the latest possible print edition on the presumption that it has had the longest time to fix typos and other errors. It looks like the scans you found are from 1899, which is later than our scans from 1872. If you want, you can correct against the edition you found, and then update our metadata/imprint/colophon to point to the new scans. You['d also have to find scans of volume 2 of that same edition.
