### ISSUE TITLE
"Statement" needs to be pluralized

### ISSUE THREAD

**Issue by jpnance** [standardebooks/mark-twain_roughing-it#5]
https://github.com/standardebooks/mark-twain_roughing-it/blob/8df3a7c4c91af46998b08898e012ecfdc52e161f/src/epub/text/chapter-9.xhtml#L11

"This person's statement were not generally believed."

In Chapter IX, there's an occurrence of the word "statement" that needs to be pluralized to "statements", as it appears on page 76 of this scan of the book: https://archive.org/details/in.ernet.dli.2015.261235/page/n78/mode/1up

The error also shows up in the Project Gutenberg text so I'll send the errata over to them as well.

**Comment by acabal** [comment]
Thanks, this should be fixed now!

If you're still reading the book, it might be easier for you to keep track of any typos and report them all at once. Probably less work than opening any number of Github issues.

**Comment by jpnance** [comment]
Yeah, I'm happy to do that if that's your preference. I didn't want to make assumptions about your workflow and I also didn't want to forget to report the issues at all but I can try to batch them up going forward.
