### ISSUE TITLE
Consider updating reference scan to 1913 edition

### ISSUE THREAD

**Issue by jpnance** [standardebooks/mark-twain_roughing-it#7]
It's come to my attention that the Volume II of the 1899 edition of "Roughing It" that I've been using is missing at least a couple of pages (62 and 63). I didn't notice anything worth correcting on those pages but, in my investigation, I did uncover an even later edition of "Roughing It"--again in two volumes--published in 1913.

Volume I: https://archive.org/details/acv6910.0001.001.umich.edu
Volume II: https://archive.org/details/acv6910.0001.002.umich.edu

If the 1899 edition becomes problematic for any reason, it would be worth considering using the 1913 edition as a reference instead. For now, though, I don't think any action is needed and I open this issue only to preserve my findings.

**Comment by acabal** [comment]
If the 1913 has all the pages and is later then we should use it anyway. The later the better. If that's the case can you open a PR?

**Comment by jpnance** [comment]
I took a very quick look through the 1913 scan and it appears to have all the pages. In a small number of places that I saw, there were physical markings on the text (and even a doodle here and there!) but nothing that seemed to render the scan unusable or unreliable. I'll open a PR and we'll go from there.

**Comment by jpnance** [comment]
The 1899 edition also appears to be missing pages 118 and 119 in Volume II, which is another mark in favor of moving to the 1913 edition.
